/**
 * Notifications API module.
 * Retrieves and manages user notifications (read status, counts).
 * @module
 */
import { request } from './client'

/** A user notification generated by the system. */
export interface Notification {
  /** Unique notification identifier. */
  id: number
  /** Short notification title. */
  title: string
  /** Full notification message body. */
  message: string
  /** Notification type (GENERAL, TEMPERATURE_ALERT, DEVIATION_ASSIGNED, TASK_DUE). */
  type: string
  /** Whether the notification has been read. */
  read: boolean
  /** ID of the referenced entity (deviation, temperature log, etc.), or null. */
  referenceId: number | null
  /** Type of the referenced entity, or null. */
  referenceType: string | null
  /** ISO-8601 creation timestamp. */
  createdAt: string
}

/** Notification API methods. */
export const notificationApi = {
  /** Fetches all notifications for the current user. */
  list: () => request<Notification[]>('/notifications'),

  /** Returns the count of unread notifications. */
  unreadCount: () => request<number>('/notifications/unread-count'),

  /**
   * Marks a single notification as read.
   * @param id - Notification identifier
   */
  markAsRead: (id: number) => request<void>(`/notifications/${id}/read`, { method: 'PUT' }),

  /** Marks all notifications as read for the current user. */
  markAllAsRead: () => request<void>('/notifications/read-all', { method: 'PUT' }),
}
