name: Deploy

on:
  push:
    branches: [ "master" ]

concurrency:
  group: production-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run deployment
        run: /home/student/deployment/deploy.sh
